import img1 from "src/assets/clothes/1.jpeg";
import img2 from "src/assets/sellingSlider/2.jpeg";
import img3 from "src/assets/sellingSlider/3.jpeg";

const brands = ["apple", "samsung", "Readme", "oppo", "zara", "shein"];
const ratings = [5, 4.5, 4, 3.5, 3];
const size = ["Small", "Medium", "Large", "Xl", "2xl", "3xl"];
const colors = [
  { name: "أحمر", hex: "#FF0000" }, // Red
  { name: "أصفر", hex: "#FFFF00" }, // Yellow
  { name: "أزرق", hex: "#0000FF" }, // Blue
  { name: "لبني", hex: "#87CEEB" }, // Light Blue (Lavender)
  { name: "أسود", hex: "#000000" }, // Black
  { name: "أخضر", hex: "#008000" }, // Green
  { name: "رمادي", hex: "#808080" }, // Gray
  { name: "ذهبي", hex: "#FFD700" }, // Gold
];

const productStates = ["جديد", "مجدد"];

const categories = [
  {
    title: "نساء",
    subCategories: ["ملابس", "احذية", "جواهر", "اكسسوارات", "موبايل", "الاجهزة الذكية"],
  },
  {
    title: "رجال",
    subCategories: ["ملابس", "احذية", "جواهر", "اكسسوارات", "موبايل", "الاجهزة الذكية"],
  },
  {
    title: "أطفال",
    subCategories: ["ملابس", "احذية", "جواهر", "اكسسوارات", "موبايل", "الاجهزة الذكية"],
  },
];

const products = [
  {
    id: 1,
    img: img1,
    title: "قميص رجالي منسوج بأزرار وياقة بولو وأكمام طويلة",
    starts: 5,
    sellingCount: 128,
    price: 1000,
    discountedPrice: 800,
    ProductImages: 4,
    brand: "zara",
    size: "Large",
    color: "أزرق",
    productState: "جديد",
    category: "ملابس",
  },
  {
    id: 1,
    img: img1,
    title: "قميص رجالي منسوج بأزرار وياقة بولو وأكمام طويلة",
    starts: 5,
    sellingCount: 128,
    price: 1000,
    discountedPrice: 800,
    ProductImages: 4,
    brand: "zara",
    size: "Large",
    color: "أزرق",
    productState: "جديد",
    category: "ملابس",
  },
  {
    id: 1,
    img: img1,
    title: "قميص رجالي منسوج بأزرار وياقة بولو وأكمام طويلة",
    starts: 5,
    sellingCount: 128,
    price: 1000,
    discountedPrice: 800,
    ProductImages: 4,
    brand: "zara",
    size: "Large",
    color: "أزرق",
    productState: "جديد",
    category: "ملابس",
  },
  {
    id: 1,
    img: img1,
    title: "قميص رجالي منسوج بأزرار وياقة بولو وأكمام طويلة",
    starts: 5,
    sellingCount: 128,
    price: 1000,
    discountedPrice: 800,
    ProductImages: 4,
    brand: "zara",
    size: "Large",
    color: "أزرق",
    productState: "جديد",
    category: "ملابس",
  },
  {
    id: 1,
    img: img1,
    title: "قميص رجالي منسوج بأزرار وياقة بولو وأكمام طويلة",
    starts: 5,
    sellingCount: 128,
    price: 1000,
    discountedPrice: 800,
    ProductImages: 4,
    brand: "zara",
    size: "Large",
    color: "أزرق",
    productState: "جديد",
    category: "ملابس",
  },
  {
    id: 1,
    img: img1,
    title: "قميص رجالي منسوج بأزرار وياقة بولو وأكمام طويلة",
    starts: 5,
    sellingCount: 128,
    price: 1000,
    discountedPrice: 800,
    ProductImages: 4,
    brand: "zara",
    size: "Large",
    color: "أزرق",
    productState: "جديد",
    category: "ملابس",
  },
  {
    id: 1,
    img: img1,
    title: "قميص رجالي منسوج بأزرار وياقة بولو وأكمام طويلة",
    starts: 5,
    sellingCount: 128,
    price: 1000,
    discountedPrice: 800,
    ProductImages: 4,
    brand: "zara",
    size: "Large",
    color: "أزرق",
    productState: "جديد",
    category: "ملابس",
  },
  {
    id: 1,
    img: img1,
    title: "قميص رجالي منسوج بأزرار وياقة بولو وأكمام طويلة",
    starts: 5,
    sellingCount: 128,
    price: 1000,
    discountedPrice: 800,
    ProductImages: 4,
    brand: "zara",
    size: "Large",
    color: "أزرق",
    productState: "جديد",
    category: "ملابس",
  },
  {
    id: 1,
    img: img1,
    title: "قميص رجالي منسوج بأزرار وياقة بولو وأكمام طويلة",
    starts: 5,
    sellingCount: 128,
    price: 1000,
    discountedPrice: 800,
    ProductImages: 4,
    brand: "zara",
    size: "Large",
    color: "أزرق",
    productState: "جديد",
    category: "ملابس",
  },
  {
    id: 1,
    img: img1,
    title: "قميص رجالي منسوج بأزرار وياقة بولو وأكمام طويلة",
    starts: 5,
    sellingCount: 128,
    price: 1000,
    discountedPrice: 800,
    ProductImages: 4,
    brand: "zara",
    size: "Large",
    color: "أزرق",
    productState: "جديد",
    category: "ملابس",
  },
  {
    id: 1,
    img: img1,
    title: "قميص رجالي منسوج بأزرار وياقة بولو وأكمام طويلة",
    starts: 5,
    sellingCount: 128,
    price: 1000,
    discountedPrice: 800,
    ProductImages: 4,
    brand: "zara",
    size: "Large",
    color: "أزرق",
    productState: "جديد",
    category: "ملابس",
  },
  {
    id: 1,
    img: img1,
    title: "قميص رجالي منسوج بأزرار وياقة بولو وأكمام طويلة",
    starts: 5,
    sellingCount: 128,
    price: 1000,
    discountedPrice: 800,
    ProductImages: 4,
    brand: "zara",
    size: "Large",
    color: "أزرق",
    productState: "جديد",
    category: "ملابس",
  },
  {
    id: 1,
    img: img1,
    title: "قميص رجالي منسوج بأزرار وياقة بولو وأكمام طويلة",
    starts: 5,
    sellingCount: 128,
    price: 1000,
    discountedPrice: 800,
    ProductImages: 4,
    brand: "zara",
    size: "Large",
    color: "أزرق",
    productState: "جديد",
    category: "ملابس",
  },
  {
    id: 1,
    img: img1,
    title: "قميص رجالي منسوج بأزرار وياقة بولو وأكمام طويلة",
    starts: 5,
    sellingCount: 128,
    price: 1000,
    discountedPrice: 800,
    ProductImages: 4,
    brand: "zara",
    size: "Large",
    color: "أزرق",
    productState: "جديد",
    category: "ملابس",
  },
  {
    id: 1,
    img: img1,
    title: "قميص رجالي منسوج بأزرار وياقة بولو وأكمام طويلة",
    starts: 5,
    sellingCount: 128,
    price: 1000,
    discountedPrice: 800,
    ProductImages: 4,
    brand: "zara",
    size: "Large",
    color: "أزرق",
    productState: "جديد",
    category: "ملابس",
  },
  {
    id: 1,
    img: img1,
    title: "قميص رجالي منسوج بأزرار وياقة بولو وأكمام طويلة",
    starts: 5,
    sellingCount: 128,
    price: 1000,
    discountedPrice: 800,
    ProductImages: 4,
    brand: "zara",
    size: "Large",
    color: "أزرق",
    productState: "جديد",
    category: "ملابس",
  },
  {
    id: 1,
    img: img1,
    title: "قميص رجالي منسوج بأزرار وياقة بولو وأكمام طويلة",
    starts: 5,
    sellingCount: 128,
    price: 1000,
    discountedPrice: 800,
    ProductImages: 4,
    brand: "zara",
    size: "Large",
    color: "أزرق",
    productState: "جديد",
    category: "ملابس",
  },
  {
    id: 1,
    img: img1,
    title: "قميص رجالي منسوج بأزرار وياقة بولو وأكمام طويلة",
    starts: 5,
    sellingCount: 128,
    price: 1000,
    discountedPrice: 800,
    ProductImages: 4,
    brand: "zara",
    size: "Large",
    color: "أزرق",
    productState: "جديد",
    category: "ملابس",
  },
  {
    id: 2,
    img: img2,
    title: "موبايل آيفون 16 بسعة 128 جيجابايت من آبل - لون أبيض",
    starts: 4.5,
    sellingCount: 95,
    price: 1200,
    discountedPrice: 1100,
    ProductImages: 4,
    brand: "apple",
    size: "Medium",
    color: "أبيض",
    productState: "جديد",
    category: "إلكترونيات",
  },
  {
    id: 3,
    img: img3,
    title: "ساعة ذكية من سامسونج - لون أسود",
    starts: 3.5,
    sellingCount: 75,
    price: 500,
    discountedPrice: 450,
    ProductImages: 4,
    brand: "samsung",
    size: "Small",
    color: "أسود",
    productState: "مجدد",
    category: "إلكترونيات",
  },
  {
    id: 3,
    img: img3,
    title: "ساعة ذكية من سامسونج - لون أسود",
    starts: 3.5,
    sellingCount: 75,
    price: 500,
    discountedPrice: 450,
    ProductImages: 4,
    brand: "samsung",
    size: "Small",
    color: "أسود",
    productState: "مجدد",
    category: "إلكترونيات",
  },
  {
    id: 3,
    img: img3,
    title: "ساعة ذكية من سامسونج - لون أسود",
    starts: 3.5,
    sellingCount: 75,
    price: 500,
    discountedPrice: 450,
    ProductImages: 4,
    brand: "samsung",
    size: "Small",
    color: "أسود",
    productState: "مجدد",
    category: "إلكترونيات",
  },
  {
    id: 3,
    img: img3,
    title: "ساعة ذكية من سامسونج - لون أسود",
    starts: 3.5,
    sellingCount: 75,
    price: 500,
    discountedPrice: 450,
    ProductImages: 4,
    brand: "samsung",
    size: "Small",
    color: "أسود",
    productState: "مجدد",
    category: "إلكترونيات",
  },
  {
    id: 3,
    img: img3,
    title: "ساعة ذكية من سامسونج - لون أسود",
    starts: 3.5,
    sellingCount: 75,
    price: 500,
    discountedPrice: 450,
    ProductImages: 4,
    brand: "samsung",
    size: "Small",
    color: "أسود",
    productState: "مجدد",
    category: "إلكترونيات",
  },
  {
    id: 3,
    img: img3,
    title: "ساعة ذكية من سامسونج - لون أسود",
    starts: 3.5,
    sellingCount: 75,
    price: 500,
    discountedPrice: 450,
    ProductImages: 4,
    brand: "samsung",
    size: "Small",
    color: "أسود",
    productState: "مجدد",
    category: "إلكترونيات",
  },
  {
    id: 3,
    img: img3,
    title: "ساعة ذكية من سامسونج - لون أسود",
    starts: 3.5,
    sellingCount: 75,
    price: 500,
    discountedPrice: 450,
    ProductImages: 4,
    brand: "samsung",
    size: "Small",
    color: "أسود",
    productState: "مجدد",
    category: "إلكترونيات",
  },
  {
    id: 3,
    img: img3,
    title: "ساعة ذكية من سامسونج - لون أسود",
    starts: 3.5,
    sellingCount: 75,
    price: 500,
    discountedPrice: 450,
    ProductImages: 4,
    brand: "samsung",
    size: "Small",
    color: "أسود",
    productState: "مجدد",
    category: "إلكترونيات",
  },
  {
    id: 3,
    img: img3,
    title: "ساعة ذكية من سامسونج - لون أسود",
    starts: 3.5,
    sellingCount: 75,
    price: 500,
    discountedPrice: 450,
    ProductImages: 4,
    brand: "samsung",
    size: "Small",
    color: "أسود",
    productState: "مجدد",
    category: "إلكترونيات",
  },
  {
    id: 3,
    img: img3,
    title: "ساعة ذكية من سامسونج - لون أسود",
    starts: 3.5,
    sellingCount: 75,
    price: 500,
    discountedPrice: 450,
    ProductImages: 4,
    brand: "samsung",
    size: "Small",
    color: "أسود",
    productState: "مجدد",
    category: "إلكترونيات",
  },
  {
    id: 3,
    img: img3,
    title: "ساعة ذكية من سامسونج - لون أسود",
    starts: 3.5,
    sellingCount: 75,
    price: 500,
    discountedPrice: 450,
    ProductImages: 4,
    brand: "samsung",
    size: "Small",
    color: "أسود",
    productState: "مجدد",
    category: "إلكترونيات",
  },
  {
    id: 3,
    img: img3,
    title: "ساعة ذكية من سامسونج - لون أسود",
    starts: 3.5,
    sellingCount: 75,
    price: 500,
    discountedPrice: 450,
    ProductImages: 4,
    brand: "samsung",
    size: "Small",
    color: "أسود",
    productState: "مجدد",
    category: "إلكترونيات",
  },
  {
    id: 3,
    img: img3,
    title: "ساعة ذكية من سامسونج - لون أسود",
    starts: 3.5,
    sellingCount: 75,
    price: 500,
    discountedPrice: 450,
    ProductImages: 4,
    brand: "samsung",
    size: "Small",
    color: "أسود",
    productState: "مجدد",
    category: "إلكترونيات",
  },
  {
    id: 3,
    img: img3,
    title: "ساعة ذكية من سامسونج - لون أسود",
    starts: 3.5,
    sellingCount: 75,
    price: 500,
    discountedPrice: 450,
    ProductImages: 4,
    brand: "samsung",
    size: "Small",
    color: "أسود",
    productState: "مجدد",
    category: "إلكترونيات",
  },
  {
    id: 3,
    img: img3,
    title: "ساعة ذكية من سامسونج - لون أسود",
    starts: 3.5,
    sellingCount: 75,
    price: 500,
    discountedPrice: 450,
    ProductImages: 4,
    brand: "samsung",
    size: "Small",
    color: "أسود",
    productState: "مجدد",
    category: "إلكترونيات",
  },
  {
    id: 3,
    img: img3,
    title: "ساعة ذكية من سامسونج - لون أسود",
    starts: 3.5,
    sellingCount: 75,
    price: 500,
    discountedPrice: 450,
    ProductImages: 4,
    brand: "samsung",
    size: "Small",
    color: "أسود",
    productState: "مجدد",
    category: "إلكترونيات",
  },
  {
    id: 3,
    img: img3,
    title: "ساعة ذكية من سامسونج - لون أسود",
    starts: 3.5,
    sellingCount: 75,
    price: 500,
    discountedPrice: 450,
    ProductImages: 4,
    brand: "samsung",
    size: "Small",
    color: "أسود",
    productState: "مجدد",
    category: "إلكترونيات",
  },
  {
    id: 3,
    img: img3,
    title: "ساعة ذكية من سامسونج - لون أسود",
    starts: 3.5,
    sellingCount: 75,
    price: 500,
    discountedPrice: 450,
    ProductImages: 4,
    brand: "samsung",
    size: "Small",
    color: "أسود",
    productState: "مجدد",
    category: "إلكترونيات",
  },
  {
    id: 3,
    img: img3,
    title: "ساعة ذكية من سامسونج - لون أسود",
    starts: 3.5,
    sellingCount: 75,
    price: 500,
    discountedPrice: 450,
    ProductImages: 4,
    brand: "samsung",
    size: "Small",
    color: "أسود",
    productState: "مجدد",
    category: "إلكترونيات",
  },
  {
    id: 3,
    img: img3,
    title: "ساعة ذكية من سامسونج - لون أسود",
    starts: 3.5,
    sellingCount: 75,
    price: 500,
    discountedPrice: 450,
    ProductImages: 4,
    brand: "samsung",
    size: "Small",
    color: "أسود",
    productState: "مجدد",
    category: "إلكترونيات",
  },
  {
    id: 3,
    img: img3,
    title: "ساعة ذكية من سامسونج - لون أسود",
    starts: 3.5,
    sellingCount: 75,
    price: 500,
    discountedPrice: 450,
    ProductImages: 4,
    brand: "samsung",
    size: "Small",
    color: "أسود",
    productState: "مجدد",
    category: "إلكترونيات",
  },
  {
    id: 3,
    img: img3,
    title: "ساعة ذكية من سامسونج - لون أسود",
    starts: 3.5,
    sellingCount: 75,
    price: 500,
    discountedPrice: 450,
    ProductImages: 4,
    brand: "samsung",
    size: "Small",
    color: "أسود",
    productState: "مجدد",
    category: "إلكترونيات",
  },
  {
    id: 3,
    img: img3,
    title: "ساعة ذكية من سامسونج - لون أسود",
    starts: 3.5,
    sellingCount: 75,
    price: 500,
    discountedPrice: 450,
    ProductImages: 4,
    brand: "samsung",
    size: "Small",
    color: "أسود",
    productState: "مجدد",
    category: "إلكترونيات",
  },
  {
    id: 3,
    img: img3,
    title: "ساعة ذكية من سامسونج - لون أسود",
    starts: 3.5,
    sellingCount: 75,
    price: 500,
    discountedPrice: 450,
    ProductImages: 4,
    brand: "samsung",
    size: "Small",
    color: "أسود",
    productState: "مجدد",
    category: "إلكترونيات",
  },
  {
    id: 3,
    img: img3,
    title: "ساعة ذكية من سامسونج - لون أسود",
    starts: 3.5,
    sellingCount: 75,
    price: 500,
    discountedPrice: 450,
    ProductImages: 4,
    brand: "samsung",
    size: "Small",
    color: "أسود",
    productState: "مجدد",
    category: "إلكترونيات",
  },
  {
    id: 3,
    img: img3,
    title: "ساعة ذكية من سامسونج - لون أسود",
    starts: 3.5,
    sellingCount: 75,
    price: 500,
    discountedPrice: 450,
    ProductImages: 4,
    brand: "samsung",
    size: "Small",
    color: "أسود",
    productState: "مجدد",
    category: "إلكترونيات",
  },
  {
    id: 3,
    img: img3,
    title: "ساعة ذكية من سامسونج - لون أسود",
    starts: 3.5,
    sellingCount: 75,
    price: 500,
    discountedPrice: 450,
    ProductImages: 4,
    brand: "samsung",
    size: "Small",
    color: "أسود",
    productState: "مجدد",
    category: "إلكترونيات",
  },
  {
    id: 3,
    img: img3,
    title: "ساعة ذكية من سامسونج - لون أسود",
    starts: 3.5,
    sellingCount: 75,
    price: 500,
    discountedPrice: 450,
    ProductImages: 4,
    brand: "samsung",
    size: "Small",
    color: "أسود",
    productState: "مجدد",
    category: "إلكترونيات",
  },
  // Add more products with complete properties...
];

export { brands, ratings, size, colors, productStates, products, categories };
